import { Plus, Minus, Search } from "lucide-react";
import { useState } from "react";

const FAQSection = () => {
    const [openIndex, setOpenIndex] = useState<number | null>(null);

    const faqs = [
        {
            question: "How many certificates can I generate at once?",
            answer: "With our Starter plan, you can generate up to 50 certificates per batch. Professional and Enterprise users have unlimited generation capabilities, limited only by the size of their uploaded data (CSV/Excel files)."
        },
        {
            question: "Can I use my own custom certificate design?",
            answer: "Yes! You can upload your own design as a background image (JPG/PNG). Our AI-powered editor allows you to place dynamic text fields (Name, Date, ID, etc.) anywhere on your custom template."
        },
        {
            question: "How does digital verification work?",
            answer: "Every certificate generated by CertifyAI includes a unique Verification ID or QR code. This links to a secure hosted page on our platform where employers or institutions can verify the certificate's authenticity in seconds."
        },
        {
            question: "What file formats are supported for downloads?",
            answer: "CertifyAI supports high-resolution PDF and PNG exports. PDF is ideal for professional printing, while PNG is perfect for sharing on social media platforms like LinkedIn."
        },
        {
            question: "Is my participant data secure?",
            answer: "We prioritize security. All uploaded data is encrypted in transit and at rest. We never share your data with third parties, and it is automatically deleted from our servers after the generation session ends."
        },
        {
            question: "Can I send certificates directly via email?",
            answer: "Absolutely. Our Professional plan includes a built-in bulk emailer. You can customize the email template and even connect your own domain via SMTP to ensure certificates are delivered from your official email address."
        }
    ];

    return (
        <section id="faq" className="py-32 bg-slate-950 relative overflow-hidden">
            {/* Background Decor */}
            <div className="absolute bottom-0 right-0 w-[500px] h-[500px] bg-indigo-500/5 rounded-full blur-[100px] pointer-events-none"></div>

            <div className="max-w-3xl mx-auto px-4 relative z-10">
                <div className="text-center mb-20">
                    <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 text-sm font-semibold mb-6">
                        <Search className="w-4 h-4" />
                        Support Center
                    </div>
                    <h2 className="text-5xl md:text-6xl font-bold text-white mb-8 tracking-tight">
                        Common <span className="bg-gradient-to-r from-cyan-400 to-indigo-400 bg-clip-text text-transparent">Questions</span>
                    </h2>
                    <p className="text-xl text-slate-400 leading-relaxed">
                        Everything you need to know about processing, security, and distribution.
                    </p>
                </div>

                <div className="space-y-4">
                    {faqs.map((faq, index) => (
                        <div
                            key={index}
                            className={`group rounded-[2rem] border transition-all duration-500 ${openIndex === index
                                    ? "bg-slate-900 border-indigo-500/50 shadow-2xl"
                                    : "bg-slate-900/40 border-slate-800 hover:border-slate-700 hover:bg-slate-900/60"
                                }`}
                        >
                            <button
                                onClick={() => setOpenIndex(openIndex === index ? null : index)}
                                className="w-full px-8 py-7 flex items-center justify-between text-left"
                            >
                                <span className={`text-xl font-bold transition-colors duration-300 ${openIndex === index ? "text-indigo-300" : "text-white group-hover:text-indigo-200"
                                    }`}>
                                    {faq.question}
                                </span>
                                <div className={`flex-shrink-0 ml-4 p-2.5 rounded-xl border transition-all duration-500 ${openIndex === index
                                        ? "bg-indigo-500 border-indigo-400 text-white rotate-180"
                                        : "bg-slate-800 border-slate-700 text-slate-400 group-hover:border-slate-600"
                                    }`}>
                                    {openIndex === index ? <Minus className="w-5 h-5" /> : <Plus className="w-5 h-5" />}
                                </div>
                            </button>

                            <div className={`overflow-hidden transition-all duration-500 ease-in-out ${openIndex === index ? "max-h-[300px] opacity-100" : "max-h-0 opacity-0"
                                }`}>
                                <div className="px-8 pb-8">
                                    <div className="h-px bg-slate-800 mb-6 w-full"></div>
                                    <p className="text-slate-400 leading-relaxed text-lg">
                                        {faq.answer}
                                    </p>
                                </div>
                            </div>
                        </div>
                    ))}
                </div>
            </div>
        </section>
    );
};

export default FAQSection;
